[package]
name = "spotify-vrc-osc"
version = "0.2.0"
edition = "2021"
description = "Sends the currently playing track on Spotify to the VRChat Chatbox Keyboard via OSC"
readme = "README.md"
repository = "https://github.com/ShayBox/Spotify-VRC-OSC"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
clap-verbosity-flag = { git = "https://github.com/ShayBoxs-Forks/clap-verbosity-flag.git", version = "2.0.0" }
env_logger = "0.9.1"
log = "0.4.17"
rosc = "0.9.1"
rspotify = { version = "0.11.5", default-features = false, features = [
    "cli",
    "client-ureq",
    "ureq-rustls-tls",
] }
terminal-link = "0.1.0"
tiny_http = "0.12.0"
webbrowser = "0.8.0"

[build-dependencies]
winres = "0.1.12"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
