on:
  release:
    types: [ created ]

jobs:
  release:
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
      LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME }}
      SPOTIFY_CALLBACK: ${{ secrets.SPOTIFY_CALLBACK }}
      SPOTIFY_CLIENT: ${{ secrets.SPOTIFY_CLIENT }}
      SPOTIFY_SECRET: ${{ secrets.SPOTIFY_SECRET }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux-x86_64
            target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
            zip: vrc-osc,libchatbox.so,libclock.so,libcontrol.so,libdebug.so,liblastfm.so,libspotify.so,libsteamvr.so

          - name: macOS-Apple
            target: aarch64-apple-darwin
            runner: macos-latest
            zip: vrc-osc,libchatbox.dylib,libclock.dylib,libcontrol.dylib,libdebug.dylib,liblastfm.dylib,libspotify.dylib

          - name: macOS-Intel
            target: x86_64-apple-darwin
            runner: macos-latest
            zip: vrc-osc,libchatbox.dylib,libclock.dylib,libcontrol.dylib,libdebug.dylib,liblastfm.dylib,libspotify.dylib

          - name: Windows
            target: x86_64-pc-windows-msvc
            runner: windows-latest
            zip: vrc-osc.exe,chatbox.dll,clock.dll,control.dll,debug.dll,lastfm.dll,spotify.dll,steamvr.dll

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3

      - name: Update and Install Dependencies (Linux)
        if: ${{ matrix.runner == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libxdo-dev

      - name: Update Rust Toolchain
        run: rustup update stable

      - name: Add Rust Target
        run: rustup target add ${{ matrix.target }}

      - name: Build Release Binary (macOS)
        if: ${{ matrix.runner == 'macos-latest' }}
        run: cargo build --release --target ${{ matrix.target }} --workspace --exclude plugin-control --exclude plugin-steamvr

      - name: Build Release Binary (Other)
        if: ${{ matrix.runner != 'macos-latest' }}
        run: cargo build --release --target ${{ matrix.target }}

      - name: Create Zip Archive (Windows)
        if: ${{ matrix.runner == 'windows-latest' }}
        run: bash -c '7z a ${{ matrix.name }}.zip ./target/${{ matrix.target }}/release/{${{ matrix.zip }}}'

      - name: Create Zip Archive (Other)
        if: ${{ matrix.runner != 'windows-latest' }}
        run: zip -j ${{ matrix.name }}.zip target/${{ matrix.target }}/release/{${{ matrix.zip }}}

      - name: Upload Zip Archive
        run: gh release upload ${{ github.ref_name }} ${{ matrix.name }}.zip --clobber
